const countryCodes = {
  'Afghanistan': '🇦🇫',
  'Albania': '🇦🇱',
  'Angola': '🇦🇴',
  'Argentina': '🇦🇷',
  'Australia': '🇦🇺',
  'Austria': '🇦🇹',
  'Azerbaijan': '🇦🇿',
  'Bahrain': '🇧🇭',
  'Belgium': '🇧🇪',
  'Bolivia': '🇧🇴',
  'Bosnia and Herzegovina': '🇧🇦',
  'Brazil': '🇧🇷',
  'Cameroon': '🇨🇲',
  'Canada': '🇨🇦',
  'Chile': '🇨🇱',
  'China': '🇨🇳',
  'Colombia': '🇨🇴',
  'Congo, The Democratic Republic of the': '🇨🇩',
  'Croatia': '🇭🇷',
  'Cuba': '🇨🇺',
  'Czech Republic': '🇨🇿',
  'Dagestan': '🇷🇺',
  'Chechnya': '🇷🇺',
  'Denmark': '🇩🇰',
  'Ecuador': '🇪🇨',
  'England': '🇬🇧',
  'France': '🇫🇷',
  'Georgia': '🇬🇪',
  'Germany': '🇩🇪',
  'Guam': '🇬🇺',
  'Iceland': '🇮🇸',
  'India': '🇮🇳',
  'Indonesia': '🇮🇩',
  'Iraq': '🇮🇶',
  'Ireland': '🇮🇪',
  'Israel': '🇮🇱',
  'Italy': '🇮🇹',
  'Jamaica': '🇯🇲',
  'Japan': '🇯🇵',
  'Kazakhstan': '🇰🇿',
  'Kyrgyzstan': '🇰🇬',
  'Lebanon': '🇱🇧',
  'Lithuania': '🇱🇹',
  'Mexico': '🇲🇽',
  'Moldova': '🇲🇩',
  'Mongolia': '🇲🇳',
  'Myanmar': '🇲🇲',
  'Netherlands': '🇳🇱',
  'New Zealand': '🇳🇿',
  'Nigeria': '🇳🇬',
  'Panama': '🇵🇦',
  'Paraguay': '🇵🇾',
  'Peru': '🇵🇪',
  'Philippines': '🇵🇭',
  'Poland': '🇵🇱',
  'Portugal': '🇵🇹',
  'Romania': '🇷🇴',
  'Russia': '🇷🇺',
  'Scotland': '🇬🇧',
  'Serbia': '🇷🇸',
  'Singapore': '🇸🇬',
  'Slovakia': '🇸🇰',
  'South Africa': '🇿🇦',
  'South Korea': '🇰🇷',
  'Spain': '🇪🇸',
  'Sweden': '🇸🇪',
  'Switzerland': '🇨🇭',
  'Tajikistan': '🇹🇯',
  'Thailand': '🇹🇭',
  'Tunisia': '🇹🇳',
  'Turkey': '🇹🇷',
  'Ukraine': '🇺🇦',
  'United Arab Emirates': '🇦🇪',
  'United States': '🇺🇸',
  'Uzbekistan': '🇺🇿',
  'Venezuela': '🇻🇪',
  'Vietnam': '🇻🇳',
  'Wales': '🇬🇧',
  'Zimbabwe': '🇿🇼'
};

const FLAG_BASE_CODEPOINT = 0x1f1e6; // regional indicator symbol 'A'

export const getCountryCode = (country) => {
  const flag = countryCodes[country];
  if (!flag) return null;
  const letters = Array.from(flag).map((char) => {
    const offset = char.codePointAt(0) - FLAG_BASE_CODEPOINT;
    return String.fromCharCode(65 + offset);
  });
  return letters.join('');
};

export default countryCodes;
