NAME_FIXES = {
    # UFC RAW : Tapology,
    "SONG YADONG": "Yadong Song",
    "THOMAS GANTT": "Tommy Gantt",
    "Zhang Mingyang": "Mingyang Zhang",
    "KAI KAMAKA": "Kai Kamaka III",
    "MICHAEL PAGE": "Michael Venom Page",
    "ABDUL RAKHMAN YAKHYAEV": "ABDULRAKHMAN YAKHYAEV",
    "LEVI RODRIGUES JR.": "Levi Rodrigues",
    "MICHAEL ASWELL JR.": "Michael Aswell",
    "NARIMAN ABBASSOV": "NARIMAN ABBASOV",
    "ALATENGHEILI": "HEILI ALATENG",
    "JOSÉ ALDO": "JOSE ALDO",
    "JJ ALDRICH": "J.J. ALDRICH",
    "JOEL ÁLVAREZ": "JOEL ALVAREZ",
    "JÉSSICA ANDRADE": "JESSICA ANDRADE",
    "AORIQILENG": "QILENG AORI",
    "VIVIANE ARAÚJO": "VIVIANE ARAUJO",
    "JAN BŁACHOWICZ": "JAN BLACHOWICZ",
    "MANDY BÖHM": "MANDY BOHM",
    "JP BUYS": "J.P. BUYS",
    "DOOHO CHOI": "DOO HO CHOI",
    "MARCOS CONRADO JUNIOR": "MARCOS CONRADO JR.",
    "AJ DOBSON": "A.J. DOBSON",
    "MAIARA AMAJANAS DOS SANTOS": "MAIARA AMANDAJAS DOS SANTOS",
    "FREDDY EMILIANO LINARES": "EMILIANO LINARES",
    "KAUÊ FERNANDES": "KAUE FERNANDES",
    "AJ FLETCHER": "A.J. FLETCHER",
    "BILLY RAY GOFF": "BILLY GOFF",
    "DAMIR HADŽOVIĆ": "DAMIR HADZOVIC",
    "ERNESTA KARECKAITĖ": "ERNESTA KARECKAITE",
    "IAN MACHADO GARRY": "IAN GARRY",
    "UROŠ MEDIĆ": "UROS MEDIC",
    "MATEUS MENDONÇA": "MATEUS MENDONCA",
    "THIAGO MOISÉS": "THIAGO MOISES",
    "SUMUDAERJI": "SU MUDAERJI",
    "JJ OKANOVICH": "J.J. OKANOVICH",
    "JULIANNA PEÑA": "JULIANNA PENA",
    "MATĚJ PEŇÁZ": "MATEJ PENAZ",
    "JIŘÍ PROCHÁZKA": "JIRI PROCHAZKA",
    "CRISTIAN QUIÑONEZ": "CRISTIAN QUINONEZ",
    "ALEKSANDAR RAKIĆ": "ALEKSANDAR RAKIC",
    "MATEUSZ RĘBECKI": "MATEUSZ REBECKI",
    "KHALIL ROUNTREE JR.": "KHALIL ROUNTREE",
    "KLAUDIA SYGUŁA": "KLAUDIA SYGULA",
    "DUŠKO TODOROVIĆ": "DUSKO TODOROVIC",
    "FARÈS ZIAM": "FARES ZIAM",
    "JESUS AGUILAR": "JESUS SANTOS AGUILAR",
    "MARCIO ALEXANDRE": "MARCIO ALEXANDRE JR.",
    "ABUS MAGOMEDOV": "ABUSUPIYAN MAGOMEDOV",
    "ARIANE DA SILVA": "ARIANE LIPSKI DA SILVA",
    "AJ CUNNINGHAM": "A.J. CUNNINGHAM",
    "ASIKEERBAI JINENSIBIEKE": "Jinensibieke Asikeerbai",
    "ATEBA GAUTIER": "Ateba Abega Gautier",
    "BENOÎT SAINT DENIS": "Benoit St. Denis",
    "BLOOD DIAMOND": "MIKE MATHETHA",
    "CAM ROWSTON": "Cameron Rowston",
    "CHANGHO LEE": "CHANG HO LEE",
    "CHARLES RADTKE": "Charlie Radtke",
    "CHEPE MARISCAL": "Jose Mariscal",
    "DANIEL SPOHN": "DAN SPOHN",
    "CHRISTIAN OCON": "Chris Ocon",
    "DARIA ZHELEZNIAKOVA": "Darya Zheleznyakova",
    "DONAVAN BEARD": "DONOVAN BEARD",
    "DONGHUN CHOI": "DONG HUN CHOI",
    "SEUNGGUK CHOI": "SEUNG GUK CHOI",
    "JOSE MIGUEL DELGADO": "JOSE DELGADO",
    "MAIARA AMANDAJAS DOS SANTOS": "Maiara Amanajas dos Santos",
    "SEONGCHAN HONG": "Seong Chan Hong",
    "KOYA KANDA": "KOUYA KANDA",
    "SEOKHYEON KO": "Seok Hyun Ko",
    "JEONGYEONG LEE": "Jeong Yeong Lee",
    "EDUARDO MATIAS TORRES": "EDUARDO TORRES",
    "HYUNSUNG PARK": "Hyun Sung Park",
    "JUNYONG PARK": "Jun Yong Park",
    "WENDRI PATILIMA": "Windri Patilima",
    "RONGZHU": "Zhu Rong",
    "RAMAZAN TEMIROV": "Ramazonbek Temirov",
    "JORDAN VUCENIC": "Jordan Vucenic",
    "JOSHUA WANG-KIM": "Josh Wang Kim",
    "JOOSANG YOO": "Joo Sang Yoo",
    "SUYOUNG YOU": "Su Young You",
    "GABE GREEN": "gabriel green",
    "JOHNNY MUNOZ": "Johnny Munoz Jr.",
    "JOSÉ HENRIQUE": "Jose Henrique Souza",
    "JUAN ANDRES LUNA": "Juan Andres Luna Martinetti",
    "KELLY VELASCO": "Kelly McGill-Velasco",
    "KHAOS WILLIAMS": "Kalinn Williams",
    "KING GREEN": "BOBBY GREEN",
    "LI JINGLIANG": "Jingliang Li",
    "LI KAIWEN": "Kaiwen Li",
    "LOMA LOOKBOONMEE": "Konklak Suphisara",
    "LONE’ER KAVANAGH": "Lone'er Kavanagh",
    "LOOPY GODINEZ": "Lupita Godinez",
    "LU ZHENGYONG": "Zhengyong Lu",
    "MAHESHATE": "Maheshate Hayisaer",
    "MARIO SOUSA": "Mario Filipe de Sousa",
    "MATEO VOGEL": "Mateo Alejandro Vogel",
    "MIZUKI": "Mizuki Inoue",
    "MUHAMMAD NAIMOV": "Muhammadjon Naimov",
    "MURTAZA TALHA": "Murtaza Talha Ali",
    "OZZY DIAZ": "Osman Diaz",
    "PATCHY MIX": "Patrick Mix",
    "PATRICIO PITBULL": "Patricio Freire",
    "PHIL ROWE": "Philip Rowe",
    "RENATO MOICANO": "Renato Carneiro",
    "REYES CORTEZ": "Reyes Cortez Jr.",
    "RICK PALACIOS": "Ricky Palacios",
    "RICKSON ZENIDIM": "Rickson Thai Zenidim Bueno",
    "SHARA MAGOMEDOV": "Sharabutdin Magomedov",
    "SONG KENAN": "Kenan Song",
    "SONG YADONG": "Yadong Song",
    "TAIYILAKE NUERAJI": "Nueraji Taiyilake",
    "TIMMY CUAMBA": "Timothy Cuamba",
    "TUCO TOKKOS": "George Tokkos",
    "VAL WOODBURN": "Valentine Woodburn",
    "VINICIUS CENCI": "Vinicius Sacchelli Cenci",
    "WALDO CORTES ACOSTA": "Waldo Cortes-Acosta",
    "WUZIAZIBIEKE JIAHEFU": "Jiahefu Wuziazibieke",
    "XIAO LONG": "Long Xiao",
    "YAN XIAONAN": "Xiaonan Yan",
    "YIZHA": "Zha Yi",
    "ZACH BORREGO": "Zachary Borrego",
    "ZHANG MINGYANG": "Mingyang Zhang",
    "ZHANG WEILI": "Weili Zhang",
    "ABDUL AZEEM BADAKHSHI": "Abdul Azim Badakhshi",
    "FABIO AGU": "Fabio Aguiar",
    "FENG PENGCHAO": "Pengchao Feng",
    "KEIFER ROBERTS": "Keifer Michael Roberts",
    "LU KAI": "KAI LU",
    "MAIARA AMAJANAS DOS SANTOS": "Maiara Amanajas dos Santos",
    "RAFAEL CERQUEIRA": "Raffael Cerqueira",
    "SANGWOOK KIM": "Sang Wook Kim"
}

POWER_SLAP = {
    "CAMERON BATES",
    "CODY BELISLE",
    "MICHAEL BONNETTE",
    "BRANDEN BORDEAUX",
    "NATE BURNARD",
    "CORY CORBIN",
    "BRIAN ELLIS",
    "HARRISON GARCIA",
    "LOGAN GREENHALGH",
    "GARRETT GRIMES",
    "FRANK HOLLAND",
    "TOP NOI KIWRAM",
    "AARON LOTT",
    "JESSE MARIOTTI",
    "DALLAS MARRON",
    "SEAN MCINERNEY",
    "DOMINIK MELENDEZ",
    "MARTIN MISHTAKU",
    "NAIR NELIKYAN",
    "STEVE REGMAN",
    "VINEESH SUBRAHMANYAN",
    "EVAN SWEESY",
    "MONTREL TALBERT",
    "TESTY TEST",
    "TIMOTHY THOMAS",
    "AUSTIN WALL",
    "DAKOTA WEIGHER",
    "BRIAN JACKSON"
}

TAPOLOGY_FIXES = {
    # TAPOLOGY : UFC RAW
    "Ben Johnston": "Benjamin Johnston",
    "Yadong Song": "SONG YADONG",
    "Tommy Gantt": "THOMAS GANTT",
    "Mingyang Zhang": "Zhang Mingyang",
    "Kai Kamaka III": "KAI KAMAKA",
    "DOO HO CHOI": "DOOHO CHOI",
    "Adrian Luna Martinetti": "JUAN MARTINETTI",
    "Michael Venom Page": "Michael Page",
    "A. Al-Selwady": "ABDUL-KAREEM AL-SELWADY",
    "Jeong Yeong Lee": "JEONGYEONG LEE",
    "Robert Ruchała": "ROBERT RUCHALA",
    "Shaqueme Rock": "SHEM ROCK",
    "D. Silva de Andrade": "DOUGLAS SILVA DE ANDRADE",
    "Jakub Wikłacz": "JAKUB WIKLACZ",
    "Jean-Paul Lebosnoyani": "JEAN PAUL LEBOSNOYANI",
    "JOSE MEDINA": "JOSE DANIEL MEDINA",
    "Kangjie Zhu": "ZHU KANGJIE",
    "Long Xiao": "XIAO LONG",
    "N. Tumendemberel": "NYAMJARGAL TUMENDEMBEREL",
    "Sang Uk Kim": "SANGWOOK KIM",
    "Seok Hyeon Ko": "SEOKHYEON KO",
    "Su Young You": "SUYOUNG YOU",
    "Benoit Saint-Denis": "BENOÎT SAINT DENIS",
    "ARIANE LIPSKI DA SILVA": "Ariane Da Silva",
    "CONG WANG": "WANG CONG",
    "Darya Zheleznyakova": "DARIA ZHELEZNIAKOVA",
    "JOO SANG YOO": "JOOSANG YOO",
    "JUN YONG PARK": "JUNYONG PARK",
    "Klaudia Syguła": "KLAUDIA SYGUŁA",
    "Raffael Cerqueira": "RAFAEL CERQUEIRA",
    "SEOK HYUN KO": "SEOKHYEON KO",
    "WALDO CORTES-ACOSTA": "WALDO CORTES ACOSTA",
    "ZACH REESE": "ZACHARY REESE",
    "Jose Delgado": "Jose Miguel Delgado",
    "Lone'er Kavanagh": "LONE’ER KAVANAGH",
    "Lupita Godinez": "Loopy Godinez",
    "Michał Oleksiejczuk": "MICHAL OLEKSIEJCZUK",
    "Diego Henrique": "DIEGO HENRIQUE DA SILVA"
}

UFC_ROSTER = {
    "Sulangrangbo": "https://www.ufc.com/athlete/sulang-rangbo",
    "Keiichiro Nakamura": "https://www.ufc.com/athlete/keiichiro-nakamura",
    "Dom Mar Fan": "https://www.ufc.com/athlete/dom-mar-fan",
    "Lawrence Lui": "https://www.ufc.com/athlete/lawrence-lui",
    "Jon Jones": "https://www.ufc.com/athlete/jon-jones",
    "Brandon Royval": "https://www.ufc.com/athlete/brandon-royval",
    "Adam Fugitt": "https://www.ufc.com/athlete/adam-fugitt",
    "Jeka Saragih": "https://www.ufc.com/athlete/jeka-saragih",
    "Rayanne dos Santos": "https://www.ufc.com/athlete/rayanne-dos-santos",
    "Umar Nurmagomedov": "https://www.ufc.com/athlete/umar-nurmagomedov",
    "Tatsuro Taira": "https://www.ufc.com/athlete/tatsuro-taira",
    "Manel Kape": "https://www.ufc.com/athlete/manel-kape",
    "Asu Almabayev": "https://www.ufc.com/athlete/assu-almabayev",
    "Steve Erceg": "https://www.ufc.com/athlete/steve-erceg",
    "Tagir Ulanbekov": "https://www.ufc.com/athlete/tagir-ulanbekov",
    "Marcus Mcghee": "https://www.ufc.com/athlete/marcus-mcghee",
    "Vinicius Oliveira": "https://www.ufc.com/athlete/vinicius-oliveira",
    "Ilia Topuria": "https://www.ufc.com/athlete/ilia-topuria",
    "Jean Silva": "https://www.ufc.com/athlete/jean-silva-lord",
    "David Onama": "https://www.ufc.com/athlete/david-onama",
    "Paddy Pimblett": "https://www.ufc.com/athlete/paddy-pimblett",
    "Michael Chandler": "https://www.ufc.com/athlete/michael-chandler",
    "Joel Alvarez": "https://www.ufc.com/athlete/joel-alvarez",
    "Jack Della Maddalena": "https://www.ufc.com/athlete/jack-della-maddalena",
    "Ian Machado Garry": "https://www.ufc.com/athlete/ian-garry",
    "Joaquin Buckley": "https://www.ufc.com/athlete/joaquin-buckley",
    "Michael Morales": "https://www.ufc.com/athlete/michael-morales",
    "Carlos Prates": "https://www.ufc.com/athlete/carlos-prates",
    "Dricus Du Plessis": "https://www.ufc.com/athlete/dricus-du-plessis",
    "Abus Magomedov": "https://www.ufc.com/athlete/abus-magomedov",
    "Alex Pereira": "https://www.ufc.com/athlete/alex-pereira",
    "Carlos Ulberg": "https://www.ufc.com/athlete/carlos-ulberg",
    "Zhang Mingyang": "https://www.ufc.com/athlete/zhang-mingyang",
    "Jailton Almeida": "https://www.ufc.com/athlete/jailton-almeida",
    "Shamil Gaziev": "https://www.ufc.com/athlete/shamil-gaziev",
    "Waldo Cortes Acosta": "https://www.ufc.com/athlete/waldo-cortes-acosta",
    "Mick Parkin": "https://www.ufc.com/athlete/mick-parkin",
    "Martin Buday": "https://www.ufc.com/athlete/martin-buday",
    "Iasmin Lucindo": "https://www.ufc.com/athlete/iasmin-lucindo",
    "Tabatha Ricci": "https://www.ufc.com/athlete/tabatha-ricci",
    "Loopy Godinez": "https://www.ufc.com/athlete/loopy-godinez",
    "Denise Gomes": "https://www.ufc.com/athlete/denise-gomes",
    "Jasmine Jasudavicius": "https://www.ufc.com/athlete/jasmine-jasudavicius",
    "Miranda Maverick": "https://www.ufc.com/athlete/miranda-maverick",
    "Karine Silva": "https://www.ufc.com/athlete/karine-silva",
    "Casey O'Neill": "https://www.ufc.com/athlete/casey-oneill",
    "Kayla Harrison": "https://www.ufc.com/athlete/kayla-harrison",
    "Ailin Perez": "https://www.ufc.com/athlete/ailin-perez",
    "Jacqueline Cavalcanti": "https://www.ufc.com/athlete/jacqueline-cavalcanti",
    "Nora Cornolle": "https://www.ufc.com/athlete/nora-cornolle",
    "Joselyne Edwards": "https://www.ufc.com/athlete/joselyne-edwards",
    "Chelsea Chandler": "https://www.ufc.com/athlete/chelsea-chandler",
    "Amir Albazi": "https://www.ufc.com/athlete/amir-albazi",
    "Khamzat Chimaev": "https://www.ufc.com/athlete/khamzat-chimaev",
    "Jose Miguel Delgado": "https://www.ufc.com/athlete/jose-delgado",
    "Steve Garcia": "https://www.ufc.com/athlete/steve-garcia",
    "Jamey-Lyn Horth": "https://www.ufc.com/athlete/jamey-lyn-horth",
    "Bruno Silva": "https://www.ufc.com/athlete/bruno-silva",
    "Tofiq Musayev": "https://www.ufc.com/athlete/tofiq-musayev",
    "Sebastian Szalay": "https://www.ufc.com/athlete/sebastian-szalay",
    "Yi Sak Lee": "https://www.ufc.com/athlete/yi-sak-lee",   
    "Tyrell Fortune": "https://www.ufc.com/athlete/tyrell-fortune",
    "Dakota Hope": "https://www.ufc.com/athlete/dakota-hope",
    "Gokhan Saricam": "https://www.ufc.com/athlete/gokhan-saricam",
    "Julien Leblanc": "https://www.ufc.com/athlete/julien-leblanc",
    "Benjamin Johnston": "https://www.ufc.com/athlete/benjamin-johnston",
    "Jamie Siraj": "https://www.ufc.com/athlete/jamie-siraj",
    "Jingnan Xiong": "https://www.ufc.com/athlete/jingnan-xiong"
}