NAME_FIXES = {
    "NARIMAN ABBASSOV": "NARIMAN ABBASOV",
    "ALATENGHEILI": "HEILI ALATENG",
    "JOSÉ ALDO": "JOSE ALDO",
    "JJ ALDRICH": "J.J. ALDRICH",
    "JOEL ÁLVAREZ": "JOEL ALVAREZ",
    "JÉSSICA ANDRADE": "JESSICA ANDRADE",
    "AORIQILENG": "QILENG AORI",
    "VIVIANE ARAÚJO": "VIVIANE ARAUJO",
    "JAN BŁACHOWICZ": "JAN BLACHOWICZ",
    "MANDY BÖHM": "MANDY BOHM",
    "JP BUYS": "J.P. BUYS",
    "DOOHO CHOI": "DOO HO CHOI",
    "MARCOS CONRADO JUNIOR": "MARCOS CONRADO JR.",
    "JOSE DANIEL MEDINA": "JOSE DANIEL MEDINA RIVERO",
    "AJ DOBSON": "A.J. DOBSON",
    "MAIARA AMAJANAS DOS SANTOS": "MAIARA AMANDAJAS DOS SANTOS",
    "FREDDY EMILIANO LINARES": "EMILIANO LINARES",
    "KAUÊ FERNANDES": "KAUE FERNANDES",
    "AJ FLETCHER": "A.J. FLETCHER",
    "BILLY RAY GOFF": "BILLY GOFF",
    "DAMIR HADŽOVIĆ": "DAMIR HADZOVIC",
    "ERNESTA KARECKAITĖ": "ERNESTA KARECKAITE",
    "IAN MACHADO GARRY": "IAN GARRY",
    "UROŠ MEDIĆ": "UROS MEDIC",
    "MATEUS MENDONÇA": "MATEUS MENDONCA",
    "THIAGO MOISÉS": "THIAGO MOISES",
    "SUMUDAERJI": "SU MUDAERJI",
    "JJ OKANOVICH": "J.J. OKANOVICH",
    "JULIANNA PEÑA": "JULIANNA PENA",
    "MATĚJ PEŇÁZ": "MATEJ PENAZ",
    "JIŘÍ PROCHÁZKA": "JIRI PROCHAZKA",
    "CRISTIAN QUIÑONEZ": "CRISTIAN QUINONEZ",
    "ALEKSANDAR RAKIĆ": "ALEKSANDAR RAKIC",
    "MATEUSZ RĘBECKI": "MATEUSZ REBECKI",
    "KHALIL ROUNTREE JR.": "KHALIL ROUNTREE",
    "KLAUDIA SYGUŁA": "KLAUDIA SYGULA",
    "DUŠKO TODOROVIĆ": "DUSKO TODOROVIC",
    "FARÈS ZIAM": "FARES ZIAM",
    "JESUS AGUILAR": "JESUS SANTOS AGUILAR",
    "MARCIO ALEXANDRE": "MARCIO ALEXANDRE JR.",
    "ABUS MAGOMEDOV": "ABUSUPIYAN MAGOMEDOV",
    "ARIANE DA SILVA": "ARIANE LIPSKI DA SILVA",
    "AJ CUNNINGHAM": "A.J. CUNNINGHAM",
    "ASIKEERBAI JINENSIBIEKE": "Jinensibieke Asikeerbai",
    "ATEBA GAUTIER": "Ateba Abega Gautier",
    "BENOIT SAINT DENIS": "Benoit St. Denis",
    "BLOOD DIAMOND": "MIKE MATHETHA",
    "CAM ROWSTON": "Cameron Rowston",
    "CHANGHO LEE": "CHANG HO LEE",
    "CHARLES RADTKE": "Charlie Radtke",
    "CHEPE MARISCAL": "Jose Mariscal",
    "DANIEL SPOHN": "DAN SPOHN",
    "CHRISTIAN OCON": "Chris Ocon",
    "DARIA ZHELEZNIAKOVA": "Darya Zheleznyakova",
    "DONAVAN BEARD": "DONOVAN BEARD",
    "DONGHUN CHOI": "DONG HUN CHOI",
    "SEUNGGUK CHOI": "SEUNG GUK CHOI",
    "HENRIQUE DA SILVA LOPES": "Diego Henrique da Silva",
    "JOSE DANIEL MEDINA RIVERO": "JOSE MEDINA",
    "JOSE MIGUEL DELGADO": "JOSE DELGADO",
    "MAIARA AMANDAJAS DOS SANTOS": "Maiara Amanajas dos Santos",
    "SEONGCHAN HONG": "Seong Chan Hong",
    "KOYA KANDA": "KOUYA KANDA",
    "SEOKHYEON KO": "Seok Hyun Ko",
    "JEONGYEONG LEE": "Jeong Yeong Lee",
    "EDUARDO MATIAS TORRES": "EDUARDO TORRES",
    "HYUNSUNG PARK": "Hyun Sung Park",
    "JUNYONG PARK": "Jun Yong Park",
    "WENDRI PATILIMA": "Windri Patilima",
    "RONGZHU": "Zhu Rong",
    "RAMAZAN TEMIROV": "Ramazonbek Temirov",
    "JORDAN VUCENIC": "Jordan Vucenic",
    "JOSHUA WANG-KIM": "Josh Wang Kim",
    "JOOSANG YOO": "Joo Sang Yoo",
    "SUYOUNG YOU": "Su Young You",
    "GABE GREEN": "gabriel green",
    "JOHNNY MUNOZ": "Johnny Munoz Jr.",
    "JOSÉ HENRIQUE": "Jose Henrique Souza",
    "JUAN ANDRES LUNA": "Juan Andres Luna Martinetti",
    "KELLY VELASCO": "Kelly McGill-Velasco",
    "KHAOS WILLIAMS": "Kalinn Williams",
    "KING GREEN": "BOBBY GREEN",
    "LI JINGLIANG": "Jingliang Li",
    "LI KAIWEN": "Kaiwen Li",
    "LOMA LOOKBOONMEE": "Konklak Suphisara",
    "LONE’ER KAVANAGH": "Lone'er Kavanagh",
    "LOOPY GODINEZ": "Lupita Godinez",
    "LU ZHENGYONG": "Zhengyong Lu",
    "MAHESHATE": "Maheshate Hayisaer",
    "MARIO SOUSA": "Mario Filipe de Sousa",
    "MATEO VOGEL": "Mateo Alejandro Vogel",
    "MIZUKI": "Mizuki Inoue",
    "MUHAMMAD NAIMOV": "Muhammadjon Naimov",
    "MURTAZA TALHA": "Murtaza Talha Ali",
    "OZZY DIAZ": "Osman Diaz",
    "PATCHY MIX": "Patrick Mix",
    "PATRICIO PITBULL": "Patricio Freire",
    "PHIL ROWE": "Philip Rowe",
    "RAFAEL LIMA DE CERQUEIRA": "Raffael Cerqueira",
    "RENATO MOICANO": "Renato Carneiro",
    "REYES CORTEZ": "Reyes Cortez Jr.",
    "RICK PALACIOS": "Ricky Palacios",
    "RICKSON ZENIDIM": "Rickson Thai Zenidim Bueno",
    "SHARA MAGOMEDOV": "Sharabutdin Magomedov",
    "SONG KENAN": "Kenan Song",
    "SONG YADONG": "Yadong Song",
    "TAIYILAKE NUERAJI": "Nueraji Taiyilake",
    "TIMMY CUAMBA": "Timothy Cuamba",
    "TUCO TOKKOS": "George Tokkos",
    "VAL WOODBURN": "Valentine Woodburn",
    "VINICIUS CENCI": "Vinicius Sacchelli Cenci",
    "WALDO CORTES ACOSTA": "Waldo Cortes-Acosta",
    "WUZIAZIBIEKE JIAHEFU": "Jiahefu Wuziazibieke",
    "XIAO LONG": "Long Xiao",
    "YAN XIAONAN": "Xiaonan Yan",
    "YIZHA": "Zha Yi",
    "ZACH BORREGO": "Zachary Borrego",
    "ZHANG MINGYANG": "Mingyang Zhang",
    "ZHANG WEILI": "Weili Zhang"
}

URL_OVERRIDES = {
    "YAIR RODRIGUEZ": "https://www.sherdog.com/fighter/Yair-Rodriguez-106305",
    "RAFAEL LIMA DE CERQUEIRA": "https://www.sherdog.com/fighter/Raffael-Cerqueira-344561",
    "DONGHUN CHOI": "https://www.sherdog.com/fighter/Dong-Hun-Choi-390131",
    "SEUNGGUK CHOI": "https://www.sherdog.com/fighter/Seung-Guk-Choi-286125",
    "HENRIQUE DA SILVA LOPES": "https://www.sherdog.com/fighter/Diego-Henrique-da-Silva-76846",
    "JOSE DANIEL MEDINA RIVERO": "https://www.sherdog.com/fighter/Jose-Medina-251871",
    "JOSE MIGUEL DELGADO": "https://www.sherdog.com/fighter/Jose-Delgado-307733",
    "MAIARA AMANDAJAS DOS SANTOS": "https://www.sherdog.com/fighter/Maiara-Amanajas-dos-Santos-77091",
    "SEONGCHAN HONG": "https://www.sherdog.com/fighter/Seong-Chan-Hong-114337",
    "KOYA KANDA": "https://www.sherdog.com/fighter/Kouya-Kanda-290771",
    "SEOKHYEON KO": "https://www.sherdog.com/fighter/Seok-Hyun-Ko-275977",
    "CHANGHO LEE": "https://www.sherdog.com/fighter/Chang-Ho-Lee-258443",
    "JEONGYEONG LEE": "https://www.sherdog.com/fighter/Jeong-Yeong-Lee-135897",
    "EDUARDO MATIAS TORRES": "https://www.sherdog.com/fighter/Eduardo-Torres-190429",
    "CHRISTIAN OCON": "https://www.sherdog.com/fighter/Chris-Ocon-194123",
    "HYUNSUNG PARK": "https://www.sherdog.com/fighter/Hyun-Sung-Park-289999",
    "JUNYONG PARK": "https://www.sherdog.com/fighter/Jun-Yong-Park-159071",
    "WENDRI PATILIMA": "https://www.sherdog.com/fighter/Windri-Patilima-323519",
    "CHARLES RADTKE": "https://www.sherdog.com/fighter/Charlie-Radtke-175669",
    "RONGZHU": "https://www.sherdog.com/fighter/Zhu-Rong-233823",
    "RAMAZAN TEMIROV": "https://www.sherdog.com/fighter/Ramazonbek-Temirov-215649",
    "JORDAN VUCENIC": "https://www.sherdog.com/fighter/Jordan-Vucenic-236825",
    "JOSHUA WANG-KIM": "https://www.sherdog.com/fighter/Josh-Wang-Kim-188773",
    "JOOSANG YOO": "https://www.sherdog.com/fighter/Joo-Sang-Yoo-387629",
    "SUYOUNG YOU": "https://www.sherdog.com/fighter/Su-Young-You-179453",
    "DARIA ZHELEZNIAKOVA": "https://www.sherdog.com/fighter/Darya-Zheleznyakova-334747",
    "DONAVAN BEARD": "https://www.sherdog.com/fighter/Donovan-Beard-310501",
    "JESUS AGUILAR": "https://www.sherdog.com/fighter/Jesus-Santos-Aguilar-203965",
    "JACK DELLA MADDALENA": "https://www.sherdog.com/fighter/Jack-Della-Maddalena-208155",
    "JON JONES": "https://www.sherdog.com/fighter/Jon-Jones-27944",
    "BENOIT SAINT DENIS": "https://www.sherdog.com/fighter/Benoit-St-Denis-317103",
    "DANIEL SPOHN": "https://www.sherdog.com/fighter/Dan-Spohn-39485",
    "AJ CUNNINGHAM": "https://www.sherdog.com/fighter/AJ-Cunningham-228033",
    "BLOOD DIAMOND": "https://www.sherdog.com/fighter/Mike-Mathetha-266635",
    "MAHESHATE": "https://www.sherdog.com/fighter/Maheshate-Hayisaer-336819",
    "MIZUKI": "https://www.sherdog.com/fighter/Mizuki-Inoue-71390",
    "MUHAMMAD NAIMOV": "https://www.sherdog.com/fighter/Muhammadjon-Naimov-228381",
    "PATRICIO PITBULL": "https://www.sherdog.com/fighter/Patricio-Freire-9960",
    "YIZHA": "https://www.sherdog.com/fighter/Zha-Yi-228277"
}

POWER_SLAP = {
    "CAMERON BATES",
    "CODY BELISLE",
    "MICHAEL BONNETTE",
    "BRANDEN BORDEAUX",
    "NATE BURNARD",
    "CORY CORBIN",
    "BRIAN ELLIS",
    "HARRISON GARCIA",
    "LOGAN GREENHALGH",
    "GARRETT GRIMES",
    "FRANK HOLLAND",
    "TOP NOI KIWRAM",
    "AARON LOTT",
    "JESSE MARIOTTI",
    "DALLAS MARRON",
    "SEAN MCINERNEY",
    "DOMINIK MELENDEZ",
    "MARTIN MISHTAKU",
    "NAIR NELIKYAN",
    "STEVE REGMAN",
    "VINEESH SUBRAHMANYAN",
    "EVAN SWEESY",
    "MONTREL TALBERT",
    "TESTY TEST",
    "TIMOTHY THOMAS",
    "AUSTIN WALL",
    "DAKOTA WEIGHER"
}

TAPOLOGY_FIXES = {
    "ADAM FUGITT": "ADAM FUGITT",  # confirm exact casing in JSON
    "ARIANE LIPSKI DA SILVA": "Ariane Da Silva",
    "BILLY RAY GOFF": "BILLY GOFF",
    "CONG WANG": "WANG CONG",
    "DARYA ZHELEZNIAKOVA": "Daria Zhelezniakova",
    "JEKA SARAGIH": "JEKA SARAGIH",  # check if accented or misspelled
    "JOO SANG YOO": "JOOSANG YOO",
    "JUN YONG PARK": "JUNYONG PARK",
    "KHALIL ROUNTREE JR.": "KHALIL ROUNTREE",
    "KLAUDIA SYGUŁA": "KLAUDIA SYGULA",
    "RAFFAEL CERQUEIRA": "RAFAEL LIMA DE CERQUEIRA",
    "RAYANNE DOS SANTOS": "RAYANNE SANTOS",  # confirm last name usage
    "SEOK HYUN KO": "SEOKHYEON KO",
    "WALDO CORTES-ACOSTA": "WALDO CORTES ACOSTA",
    "ZACH REESE": "ZACHARY REESE"  # if full name used in JSON
}

